sudo: required

language: python

python:
  - "3.6"

services:
  - docker

before_install:
- sudo service postgresql stop
# wait for postgresql to shutdown
- while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

- docker build -t cs162-flask:latest web
- docker network create -d bridge cs162-bridge-network
- docker run --name=db --network=cs162-bridge-network -d --expose 5432 -p 5432:5432/tcp  -e "POSTGRES_DB=cs162" -e "POSTGRES_USER=cs162_user" -e "POSTGRES_PASSWORD=cs162_password" postgres:alpine
- |
    while ! psql "dbname=cs162 host=127.0.0.1 user=cs162_user password=cs162_password port=5432" -c 'SELECT 1'> /dev/null 2>&1; do
      echo 'Waiting for postgres...'
      sleep 1;
    done;
- docker run --name=cs162-instance --network=cs162-bridge-network -d --expose 5000 -p 5000:5000/tcp cs162-flask

# command to install dependencies
install:
  - pip install -r tests/requirements.txt

before_script:
    # It seems to take a few seconds before flask / db accept connections, so let's snooze.
    - sleep 10
# command to run tests
script:
- python tests/int_tests.py
